### ISSUE TITLE
[BUG] 1.0.3 scam.exe reported with virus Behavior:Win32/DefenseEvasion.A!ml by Windows Defender

### ISSUE THREAD

**Issue by dev-quantum** [VRn00b/scam-blockchain#2]
**Describe the bug**
1.0.3 scam.exe reported with virus Behavior:Win32/DefenseEvasion.A!ml by Windows Defender

**To Reproduce**

Install 1.0.3 on windows 10, scam.exe gets flagged with virus and quarantined. Only GUI works, can't use CLI

**Expected behavior**
Clean install

**Comment by VRn00b** [comment]
https://www.microsoft.com/en-us/wdsi/submission/400babe4-d309-4488-9105-8246c5cd766e
you must update your defender bases

**Comment by VRn00b** [comment]
**Analyst comments:**
We have removed the detection.  Please follow the steps below to clear cached detection and obtain the latest malware definitions.
     1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender 
     2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
     3. Run "MpCmdRun.exe -SignatureUpdate"
