### ISSUE TITLE
[BUG] Failed to create scam daemon

### ISSUE THREAD

**Issue by Jsewill** [VRn00b/scam-blockchain#2]
Using a fresh installation from the master branch (0bdc6ee4051cf952be196d05d2b34a17282835ce), I receive the error message, "Failed to create the scam daemon", when running `scam start farmer`. The daemon process did start, but I'm guessing it is just failing to communicate with it to start everything else.

The log confirms this:
```2021-08-04T19:40:20.550 daemon scam.daemon.server         : INFO     Starting Daemon Server
2021-08-04T19:40:20.552 daemon scam.daemon.server         : INFO     Waiting Daemon WebSocketServer closure```

**Comment by VRn00b** [comment]
need some time to finish works

**Comment by Jsewill** [comment]
Haha. I'll leave you be. This particular bug is fixed with the latest commit.
